replicaCount: 2

image:
  repository: 181080507715.dkr.ecr.ap-south-1.amazonaws.com/my-app
  pullPolicy: IfNotPresent
  tag: "1"

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

ingress:
  enabled: false
