replicaCount: 2

image:
  repository: 181080507715.dkr.ecr.ap-south-1.amazonaws.com/my-app
  pullPolicy: IfNotPresent
  tag: "1"

service:
  type: LoadBalancer
  port: 80
  targetPort: 80


env:
  PORT: "3000"

ingress:
  enabled: false
